config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'layouts/application'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'log_out', to: 'sessions#destroy', as: 'log_out'
  get 'mypage', to: 'users#show', as: 'mypage'
  get 'mypage/my_posts', to: 'users#my_posts', as: 'my_posts'
  get 'mypage/liked_posts', to: 'users#liked_posts', as: 'liked_posts'
  resources :sessions, only: %i[create destroy]
  resources :users, only: [:update] do
    member do
      get 'posts', to: 'posts#index', as: 'posts'
      get 'liked_posts', to: 'posts#liked', as: 'liked_posts'
    end
  end

  # 投稿に対するRESTfulルーティングを生成する
  resources :posts, only: [:index, :new, :create, :edit, :update, :destroy, :show] do
    # 個別の投稿に対するlikeアクションを追加する
    member do
      post 'like' # POSTリクエストを受け取る
    end
  end

  resources :users, only: [:show, :update]

  get 'before_login', to: 'static_pages#before_login', as: 'before_login'

  # 最後に消す
  match '/_next/*path', to: proc { [200, {}, ['']] }, via: :all
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  mount_uploader :image, ImageUploader

  # userインスタンスは複数のpostインスタンスを持つことができる（１対多）
  has_many :posts

  # User と Post モデルに Like モデルを通じた関連付けを追加
  has_many :likes
  has_many :liked_posts, through: :likes, source: :post

  # バリデーションの定義
  validates :email, presence: true, uniqueness: true
  validates :name, presence: { message: "を入力してください" } # ユーザー名のバリデーションを追加
  validates :image, presence: true, format: { with: /\.(jpeg|jpg|png|heic)\z/i, message: "許可されていないファイル形式です" }

  after_initialize :set_default_image, if: :new_record?

  def set_default_image
    self.image ||= 'default_profile.png'
  end

  class << self
    def find_or_create_from_auth_hash(auth_hash)
      user_params = user_params_from_auth_hash(auth_hash)
      find_or_create_by(email: user_params[:email]) do |user|
        user.name = user_params[:name]
        user.remote_image_url = user_params[:image]
      end
    end

    def user_params_from_auth_hash(auth_hash)
      {
        name: auth_hash.info.name,
        email: auth_hash.info.email,
        image: auth_hash.info.image
      }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :update]
  before_action :check_logged_in, except: [:show]

  def show
    if @user.nil?
      redirect_to before_login_path
    else
      @posts = @user.posts
      @liked_posts = @user.liked_posts
    end
  end

  def update
    @posts = @user.posts
    @liked_posts = @user.liked_posts
    if @user.update(user_params)
      redirect_to mypage_path, notice: 'プロフィールを更新しました。'
    else
      render :show
    end
  end

  def my_posts
    @user = current_user
    @posts = @user.posts
  end

  def liked_posts
    @user = current_user
    @liked_posts = @user.liked_posts
  end

  private

  def set_user
    @user = current_user
  end

  def user_params
    params.require(:user).permit(:name, :image)
  end
end

app/views/users/_liked_posts.html.erb
<% if @liked_posts.any? %>
  <% @liked_posts.each do |post| %>
    <div class="bg-gray-100 p-4 rounded-lg shadow mb-4 flex">
    <%= image_tag post.image.url, class: "w-36 h-36 rounded-lg object-cover mb-2" if post.image.present? %>
    <div class="ml-4 w-2/3">
        <h3 class="text-lg font-semibold text-gray-700 mb-2">
          <%= link_to post.title, post_path(post), class: "text-blue-500 hover:underline" %>
        </h3>
        <p class="text-gray-600 mb-2">所在地</p>
        <p class="text-gray-600 mb-2"><%= post.address %></p>
        <div class="flex justify-end space-x-2">
        <%= form_with(url: like_post_path(post), method: :post, remote: true, html: { id: "like-form-#{post.id}", data: { turbo: false } }) do %>
            <button type="submit" class="btn btn-primary flex items-center">
            <i class="<%= current_user.likes.exists?(post: post) ? 'fas fa-thumbs-up text-black' : 'far fa-thumbs-up text-gray-400' %>" id="like-icon-<%= post.id %>"></i>
            </button>
        <% end %>
        </div>
    </div>
    </div>
  <% end %>
<% else %>
  <p>お気に入りの投稿がありません。</p>
<% end %>

app/views/users/_my_posts.html.erb
<% if @posts.any? %>
  <% @posts.each do |post| %>
    <div class="bg-gray-100 p-4 rounded-lg shadow mb-4 flex">
      <%= image_tag post.image.url, class: "w-36 h-36 rounded-lg object-cover mb-2" if post.image.present? %>
      <div class="ml-4 w-2/3">
        <h3 class="text-lg font-semibold text-gray-700 mb-2">
          <%= link_to post.title, post_path(post), class: "text-blue-500 hover:underline" %>
        </h3>
        <p class="text-gray-600 mb-2">所在地</p>
        <p class="text-gray-600 mb-2"><%= post.address %></p>
        <div class="flex justify-end space-x-2">
          <%= link_to '編集', edit_post_path(post), class: "bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded" %>
          <%= link_to '削除', post, method: :delete, data: { confirm: '本当に削除しますか？' }, class: "bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded" %>
        </div>
      </div>
    </div>
  <% end %>
<% else %>
  <p>投稿がありません。</p>
<% end %>

app/views/users/liked_posts.html.erb
<h1>お気に入りの投稿</h1>
<%= render 'users/liked_posts' %>

app/views/users/my_posts.html.erb
<h1>自分の投稿</h1>
<%= render 'users/my_posts' %>

app/views/users/show.html.erb
<div class="container mx-auto p-4">
  <h1 class="text-2xl font-bold mb-4">マイページ</h1>
  <div class="tabs mb-5">
    <a href="javascript:void(0);" class="tab mr-7 border-b-2 border-transparent hover:border-gray-300" onclick="showTab('profile')">プロフィール設定</a>
    <a href="javascript:void(0);" class="tab mr-7 border-b-2 border-transparent hover:border-gray-300" onclick="showTab('my-posts')">自分の投稿</a>
    <a href="javascript:void(0);" class="tab mr-7 border-b-2 border-transparent hover:border-gray-300" onclick="showTab('liked-posts')">お気に入りの投稿</a>
  </div>

  <div id="profile" class="tab-content">
    <%= form_with model: @user, local: true, html: { multipart: true }, data: { turbo: false } do |f| %>
      <% if @user.errors.any? %>
        <div id="error_explanation" class="text-red-500">
          <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="mb-4 mt-4">
        <%= image_tag @user.image.url, class: "w-24 h-24 rounded-full object-cover mb-2" if @user.image.present? %>
        <%= f.label :image, "プロフィール画像", class: "block text-gray-700 text-sm font-bold mb-2 inline" %>
        <%= f.file_field :image, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline", accept: "image/jpeg,image/jpg,image/png,image/heic" %>
        <span class="text-xs text-gray-500">ファイル形式：jpeg、jpg、png、heic</span>
      </div>
      <div class="mb-4">
        <%= f.label :name, "ユーザー名", class: "block text-gray-700 text-sm font-bold mb-2 inline" %>
        <span class="text-red-500 inline">*</span>
        <%= f.text_field :name, value: @user.name, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline", placeholder: "ユーザー名を入力してください" %>
      </div>
      <div class="mt-20">
        <%= f.submit "更新する", class: "bg-gray-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded" %>
      </div>
    <% end %>
  </div>

  <div id="my-posts" class="tab-content hidden">
    <%= render 'users/my_posts' %>
  </div>

  <div id="liked-posts" class="tab-content hidden">
    <%= render 'users/liked_posts' %>
  </div>
</div>

<script>
  function showTab(tabId) {
    document.querySelectorAll('.tab-content').forEach(function(content) {
      content.classList.add('hidden');
    });
    document.getElementById(tabId).classList.remove('hidden');

    document.querySelectorAll('.tab').forEach(function(tab) {
      tab.classList.remove('active', 'border-blue-500');
    });
    document.querySelector(`[onclick="showTab('${tabId}')"]`).classList.add('active', 'border-blue-500');
  }

  // ページ読み込み時に、URLのアンカーに基づいてタブを表示
  document.addEventListener('DOMContentLoaded', function() {
    const hash = window.location.hash;
    if (hash) {
      showTab(hash.substring(1)); // アンカー部分（#以降）を取得してshowTab関数に渡す
    } else {
      showTab('profile');
    }
  });

  // URLのハッシュが変更されたときにタブを表示
  window.addEventListener('hashchange', function() {
    const hash = window.location.hash;
    if (hash) {
      showTab(hash.substring(1));
    }
  });
</script>