config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'layouts/application'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'log_out', to: 'sessions#destroy', as: 'log_out'
  get 'mypage', to: 'users#show', as: 'mypage'
  get 'mypage/my_posts', to: 'users#my_posts', as: 'my_posts'
  get 'mypage/liked_posts', to: 'users#liked_posts', as: 'liked_posts'
  resources :sessions, only: %i[create destroy]
  resources :users, only: [:update] do
    member do
      get 'posts', to: 'posts#index', as: 'posts'
      get 'liked_posts', to: 'posts#liked', as: 'liked_posts'
    end
  end

  # 投稿に対するRESTfulルーティングを生成する
  resources :posts, only: [:index, :new, :create, :edit, :update, :destroy, :show] do
    # 個別の投稿に対するlikeアクションを追加する
    member do
      post 'like' # POSTリクエストを受け取る
    end
  end

  resources :users, only: [:show, :update]

  get 'before_login', to: 'static_pages#before_login', as: 'before_login'

  # 最後に消す
  match '/_next/*path', to: proc { [200, {}, ['']] }, via: :all
end

app/views/shared/_error_messages.html.erb
<%# 解説/error_messages.txt %>
<% if object.errors.any? %>
  <div id="error_explanation" class="text-red-500">
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="bg-gray-200 text-center p-4 mt-4">
  <div class="container mx-auto">
    <a href="#" class="text-black link link-hover">利用規約</a>
    <a href="#" class="text-black link link-hover">プライバシーポリシー</a>
    <a href="#" class="text-black link link-hover">お問い合わせ</a>
    <p class="text-black">© 2024 - IshikawaTrip</p>
  </div>
</footer>

app/views/shared/_header.html.erb
<header class="flex justify-between items-center w-full p-2 border-b-2">
  <%= link_to root_path do %>
    <%= image_tag "ishikawatriplogo.png", alt: "いしかわとりっぷ", width: "100" %>
  <% end %>
  <div class="flex items-center gap-3">
    <button class="text-black py-2 px-4 rounded">
      <div>
        <!-- クライアントライブラリの読み込み 下記1行を追加 -->
        <script src="https://accounts.google.com/gsi/client" async defer></script>

        <% if notice.present? %>
        <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice">
          <%= notice %></p>
        <% end %>

        <% if current_user %>
          <% if current_user.image.present? && !current_user.image.blank? %>
            <%= image_tag current_user.image.url, class: "w-12 h-12 rounded-full object-cover" %>
          <% else %>
            <%= image_tag 'default_profile.png', class: "w-12 h-12 rounded-full object-cover" %> <!-- デフォルトのプロフィール画像 -->
          <% end %>
          <%= current_user.name %>
        <% else %>
          ゲスト
          <%= button_to "Googleでログイン", "/auth/google_oauth2", method: :post, data: { turbo: false } %>
        <% end %>
      </div>
    </button>
    <i id="menuIcon" class="fas fa-bars cursor-pointer"></i>
  </div>
  <div id="menu" class="hidden absolute right-7 top-20 bg-white py-2 px-4 shadow-lg">
    <ul class="flex flex-col gap-2">
      <li><%= link_to "マイページ", mypage_path %></li>
      <li><%= link_to "投稿一覧", posts_path %></li>
      <li><%= link_to "新規投稿", new_post_path %></li>
      <% if current_user %>
      <li>
        <%= link_to "ログアウト", log_out_path %>
      </li>
      <% end %>
    </ul>
  </div>
</header>